name: Release-doinstruct

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  release:
    name: Release-doinstruct
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.0

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Dependencies
        run: pnpm i


      - name: Rename package to @doinstruct/ai-sdk-mistral
        run: |
          jq '.name = "@doinstruct/ai-sdk-mistral"' packages/mistral/package.json > packages/mistral/package.tmp.json
          mv packages/mistral/package.tmp.json packages/mistral/package.json

      - name: Rename package to @doinstruct/ai-sdk-ai
        run: |
          jq '.name = "@doinstruct/ai-sdk-ai"' packages/ai/package.json > packages/ai/package.tmp.json
          mv packages/ai/package.tmp.json packages/ai/package.json

      - name: Publish mistral package
        run: cd packages/mistral && npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm_config_registry: 'https://npm.pkg.github.com/@doinstruct'

      - name: Publish ai package
        run: cd packages/ai && npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm_config_registry: 'https://npm.pkg.github.com/@doinstruct'

      # - name: Create Release Pull Request or Publish to npm
      #   id: changesets
      #   uses: changesets/action@v1
      #   with:
      #     # This expects you to have a script called release which does a build for your packages and calls changeset publish
      #     version: pnpm ci:version
      #     publish: pnpm ci:release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}
